// Autogenerated from Pigeon (v22.7.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class ScreeshotApiException: Error {
  let code: String
  let message: String?
  let details: Any?

  init(code: String, message: String?, details: Any?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "ScreeshotApiException(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>")"
      }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? ScreeshotApiException {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

private class ScreeshotAPIPigeonCodecReader: FlutterStandardReader {
}

private class ScreeshotAPIPigeonCodecWriter: FlutterStandardWriter {
}

private class ScreeshotAPIPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ScreeshotAPIPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ScreeshotAPIPigeonCodecWriter(data: data)
  }
}

class ScreeshotAPIPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ScreeshotAPIPigeonCodec(readerWriter: ScreeshotAPIPigeonCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol ScreenshotApi {
  func enableScreenshot() throws -> Bool
  func disableScreenshot() throws -> Bool
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class ScreenshotApiSetup {
  static var codec: FlutterStandardMessageCodec { ScreeshotAPIPigeonCodec.shared }
  /// Sets up an instance of `ScreenshotApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: ScreenshotApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let enableScreenshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_channel.ScreenshotApi.enableScreenshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      enableScreenshotChannel.setMessageHandler { _, reply in
        do {
          let result = try api.enableScreenshot()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      enableScreenshotChannel.setMessageHandler(nil)
    }
    let disableScreenshotChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.native_channel.ScreenshotApi.disableScreenshot\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disableScreenshotChannel.setMessageHandler { _, reply in
        do {
          let result = try api.disableScreenshot()
          reply(wrapResult(result))
        } catch {
          reply(wrapError(error))
        }
      }
    } else {
      disableScreenshotChannel.setMessageHandler(nil)
    }
  }
}
